name: rces
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.7    # Python version 3.7
    - basemap       # mapping package
    - bottleneck    # C-optimized array functions for NumPy
    - cartopy       # Geographic plotting toolkit
    - dask          # Parallel processing library
    - h5py          # Wrapper for HDF5
    - ipython       # IPython interpreter and tools
    - jupyter       # Jupyter federation architecture
    - jupyterlab    # Jupyter Lab environment
    - matplotlib    # 2D plotting library
    - netcdf4       # Wrapper for netcdf4
    - numpy         # N-d array and numerics
    - numba         # For speeding up python code
    - pandas        # Labeled array library
    - proj4         # geographic projections
    - pyresample    # Geographic resampling tools
    - scipy         # Common math/stats/science functions
    - scikit-learn  # Macine learning library
    - scikit-image  # Image processing routines
    - statsmodels   # Regression/modeling toolkit
    - seaborn       # Statistical visualizations
    - tqdm          # Nice progress bar for longer computations
    - xarray        # N-d labeled array library
    - xgcm          # Tools for working with finite-volume grids
    - zarr          # Array storage library
    - numcodecs     # Compression library used by zarr
    - gcsfs         # Access data from Google Cloud Storage
    - s3fs          # Access data from Amazon S3